dist: xenial

language: cpp
compiler: gcc
 
addons:
  apt:
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
      - doxygen
      - graphviz
      - zlib1g-dev
      - qt5-default
      - cmake
      - cmake-data
    
script:
  - mkdir _build
  - cd _build
  - /usr/bin/cmake .. -DCMAKE_BUILD_TYPE=Release
  - make
  - /usr/bin/cpack -G DEB
