contact_links:
  - name: ğŸ™ Questions or general discussion with the community
    url: https://github.com/eclipse-ecal/ecal/discussions
    about: Use our Community Forum for general conversations that aren't meant for actionable Issues.