name: Documentation build

on:  
  push:
    branches:
      - support/v5.13
  release:
    types:
      - released
      - unpublished
      - deleted

jobs:
  documentation-build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt-get install ninja-build doxygen graphviz libprotobuf-dev libprotoc-dev protobuf-compiler libhdf5-dev

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules:  'true'
        fetch-depth: 0
        ref: 'support/v5.13'
        
    - name: Install Python requirements
      shell: bash
      run: |
        sudo apt-get -y install python3-dev python3-venv
        mkdir ".venv_build"
        python3 -m venv ".venv_build"
        source ".venv_build/bin/activate"
        pip install --upgrade pip
        pip install wheel setuptools
        pip install -r "$GITHUB_WORKSPACE/doc/requirements.txt"

    - name: CMake
      run: |
        source ".venv_build/bin/activate"
        
        mkdir "${{ runner.workspace }}/_build"
        cd "${{ runner.workspace }}/_build"
        cmake $GITHUB_WORKSPACE -G "Ninja" \
        -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=cmake/submodule_dependencies.cmake \
        -DHAS_HDF5=ON \
        -DHAS_QT=OFF \
        -DHAS_CURL=OFF \
        -DHAS_CAPNPROTO=OFF \
        -DHAS_FTXUI=ON \
        -DBUILD_DOCS=ON \
        -DBUILD_APPS=OFF \
        -DBUILD_SAMPLES=OFF \
        -DBUILD_TIME=OFF \
        -DBUILD_PY_BINDING=ON \
        -DBUILD_CSHARP_BINDING=OFF \
        -DBUILD_ECAL_TESTS=OFF \
        -DECAL_INCLUDE_PY_SAMPLES=OFF \
        -DECAL_INSTALL_SAMPLE_SOURCES=OFF \
        -DECAL_JOIN_MULTICAST_TWICE=OFF \
        -DECAL_NPCAP_SUPPORT=OFF \
        -DECAL_THIRDPARTY_BUILD_CMAKE_FUNCTIONS=ON \
        -DECAL_THIRDPARTY_BUILD_PROTOBUF=OFF \
        -DECAL_THIRDPARTY_BUILD_SPDLOG=ON \
        -DECAL_THIRDPARTY_BUILD_TINYXML2=ON \
        -DECAL_THIRDPARTY_BUILD_FINEFTP=ON \
        -DECAL_THIRDPARTY_BUILD_CURL=OFF \
        -DECAL_THIRDPARTY_BUILD_GTEST=ON \
        -DECAL_THIRDPARTY_BUILD_HDF5=OFF \
        -DECAL_THIRDPARTY_BUILD_RECYCLE=ON \
        -DECAL_THIRDPARTY_BUILD_TCP_PUBSUB=ON \
        -DECAL_THIRDPARTY_BUILD_QWT=OFF \
        -DECAL_THIRDPARTY_BUILD_YAML-CPP=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_SYSCONFDIR=/etc \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LOCALSTATEDIR=/var \
        -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu \
        -DPython_FIND_VIRTUALENV=ONLY
      shell: bash

    - name: Build Documentation
      env:
        ECAL_GH_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: cmake --build . --parallel --config Release --target documentation_sphinx
      working-directory: ${{ runner.workspace }}/_build

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ runner.workspace }}/_build/doc/html
